import { User, Shop, Category, FoodItem } from '../types';

const now = new Date().toISOString();

export const defaultUsers: User[] = [
  {
    _id: 'user-eatandfly',
    name: 'Eat & Fly Chef & Owner',
    email: 'owner@eatandfly.food',
    phone: '+91 98421 00123',
    role: 'owner',
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'user-annapoorna',
    name: 'Murugan Swaminathan',
    email: 'owner@annapoorna.com',
    phone: '+91 98421 87654',
    role: 'owner',
    createdAt: now,
    updatedAt: now,
  },
];

export const defaultShops: Shop[] = [
  {
    _id: 'shop-eatandfly',
    ownerId: 'user-eatandfly',
    name: 'Eat & Fly',
    slug: 'eat-and-fly',
    logo: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=300&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&auto=format&fit=crop&q=80',
    description: 'GOOD FOOD | GOOD LIFE • Crispy Fried Chicken, Loaded Fries, Sizzling Burgers, Fresh Waffles, Hot Chocolate & Mocktails.',
    phone: '+91 98421 00123',
    whatsappNumber: '+919842100123',
    address: 'Food Truck Hub, Main Street',
    location: 'Near Central Plaza',
    openingTime: '04:00 PM',
    closingTime: '11:30 PM',
    isOpen: true,
    currency: '₹',
    orderingEnabled: true,
    whatsappOrderingEnabled: true,
    upiId: 'eatandfly@upi',
    customTagline: 'GOOD FOOD | GOOD LIFE',
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'shop-annapoorna',
    ownerId: 'user-annapoorna',
    name: 'Annapoorna Food Truck',
    slug: 'annapoorna-food-truck',
    logo: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=300&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&auto=format&fit=crop&q=80',
    description: 'Authentic roadside hot bites, tawa fried rice, sizzling rolls & signature chillers.',
    phone: '+91 98421 87654',
    whatsappNumber: '+919842187654',
    address: 'Near Central Bus Stand',
    location: 'Erode, Tamil Nadu',
    openingTime: '05:30 PM',
    closingTime: '11:30 PM',
    isOpen: true,
    currency: '₹',
    orderingEnabled: true,
    whatsappOrderingEnabled: true,
    upiId: 'annapoornafood@upi',
    customTagline: 'Fresh & Hot From Our Food Truck Right To You!',
    createdAt: now,
    updatedAt: now,
  },
];

export const defaultCategories: Category[] = [
  // Categories for Eat & Fly
  {
    _id: 'cat-fried-chicken',
    shopId: 'shop-eatandfly',
    name: 'FRIED CHICKEN',
    description: 'Golden crunchy & juicy southern fried chicken specials',
    displayOrder: 1,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'cat-fries',
    shopId: 'shop-eatandfly',
    name: 'FRENCH FRIES',
    description: 'Crispy potato fries, peri peri seasoning & loaded cheesy platters',
    displayOrder: 2,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'cat-burgers',
    shopId: 'shop-eatandfly',
    name: 'BURGERS',
    description: 'Freshly toasted sesame buns, crispy veg & sizzling chicken patties',
    displayOrder: 3,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'cat-rolls',
    shopId: 'shop-eatandfly',
    name: 'WRAPS / ROLLS',
    description: 'Warm flaky rolls stuffed with delicious fillings and sauces',
    displayOrder: 4,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'cat-momos',
    shopId: 'shop-eatandfly',
    name: 'MOMOS',
    description: 'Hot steamed & crispy fried dumplings with spicy dipping dip',
    displayOrder: 5,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'cat-waffles',
    shopId: 'shop-eatandfly',
    name: 'SWEETS (WAFFLES)',
    description: 'Belgian waffles drenched in chocolate, biscoff, blueberry & kitkat',
    displayOrder: 6,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'cat-hot-chocolate',
    shopId: 'shop-eatandfly',
    name: 'HOT CHOCOLATE',
    description: 'Thick velvety rich cocoa served hot with marshmallows and ice cream',
    displayOrder: 7,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'cat-mojito',
    shopId: 'shop-eatandfly',
    name: 'MOJITO',
    description: 'Sparkling refreshing mint, berry & citrus crushed coolers',
    displayOrder: 8,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'cat-extra',
    shopId: 'shop-eatandfly',
    name: 'EXTRA',
    description: 'Packaging and extra cheese toppings',
    displayOrder: 9,
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
];

export const defaultFoods: FoodItem[] = [
  // ==========================================
  // 1. FRIED CHICKEN
  // ==========================================
  {
    _id: 'ef-fc-1',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-fried-chicken',
    name: 'Fried Chicken Popcorn',
    description: 'Crispy, bite-sized chicken popcorn marinated in seasoned spices and deep fried till golden crunch.',
    image: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=600&auto=format&fit=crop&q=80',
    price: 100,
    isVegetarian: false,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '6-8 mins',
    displayOrder: 1,
    tags: ['Bestseller', 'Crispy', 'Snack'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-fc-2',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-fried-chicken',
    name: 'Fried Wings (2 pcs)',
    description: 'Succulent chicken wings double-battered in crunchy flour and seasoned with aromatic herbs.',
    image: 'https://images.unsplash.com/photo-1679901170046-8e50b1812a67?w=600&auto=format&fit=crop&q=80',
    price: 90,
    isVegetarian: false,
    isAvailable: true,
    isFeatured: false,
    preparationTime: '7-9 mins',
    displayOrder: 2,
    tags: ['Wings', 'Hot'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-fc-3',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-fried-chicken',
    name: 'Fried Chicken Lollipop (2 pcs)',
    description: 'Classic frenched chicken winglets deep fried to a rich golden crust with savory dipping dip.',
    image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=600&auto=format&fit=crop&q=80',
    price: 100,
    isVegetarian: false,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '8-10 mins',
    displayOrder: 3,
    tags: ['Popular', 'Chef Pick'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-fc-4',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-fried-chicken',
    name: 'Lays Chicken',
    description: 'Tender chicken strips crusted with crunchy crushed potato chips for an irresistible crunch.',
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=600&auto=format&fit=crop&q=80',
    price: 100,
    isVegetarian: false,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '7-9 mins',
    displayOrder: 4,
    tags: ['Crunchy Special', 'Must Try'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-fc-5',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-fried-chicken',
    name: 'Fried Chicken (2 pcs)',
    description: 'Traditional southern-style crispy fried chicken pieces with juicy tender meat under a golden crust.',
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&auto=format&fit=crop&q=80',
    price: 110,
    isVegetarian: false,
    isAvailable: true,
    isFeatured: false,
    preparationTime: '8-10 mins',
    displayOrder: 5,
    tags: ['Classic', 'Juicy'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-fc-6',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-fried-chicken',
    name: 'Nashville Fried Chicken (2 pcs)',
    description: 'Fiery Nashville style hot fried chicken glazed in spiced cayenne pepper oil, paprika, and herbs.',
    image: 'https://images.unsplash.com/photo-1569058242567-93de6f36f8e6?w=600&auto=format&fit=crop&q=80',
    price: 120,
    isVegetarian: false,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '8-10 mins',
    displayOrder: 6,
    tags: ['Spicy', 'Nashville Hot'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-fc-7',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-fried-chicken',
    name: 'Spicy Fried Chicken (2 pcs)',
    description: 'Extra spiced fried chicken marinated with red chili masala, pepper, and served piping hot.',
    image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=600&auto=format&fit=crop&q=80',
    price: 120,
    isVegetarian: false,
    isAvailable: true,
    isFeatured: false,
    preparationTime: '8-10 mins',
    displayOrder: 7,
    tags: ['Fiery', 'Spicy'],
    createdAt: now,
    updatedAt: now,
  },

  // ==========================================
  // 2. FRENCH FRIES
  // ==========================================
  {
    _id: 'ef-ff-1',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-fries',
    name: 'French Fries',
    description: 'Classic salted golden potato fries fried to a light crisp and served piping hot.',
    image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=600&auto=format&fit=crop&q=80',
    price: 50,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: false,
    preparationTime: '5 mins',
    displayOrder: 1,
    tags: ['Classic', 'Veg'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-ff-2',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-fries',
    name: 'Peri Peri French Fries',
    description: 'Hot crisp french fries generously tossed in zesty, tangy African peri peri spice mix.',
    image: 'https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?w=600&auto=format&fit=crop&q=80',
    price: 60,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '5 mins',
    displayOrder: 2,
    tags: ['Peri Peri', 'Spicy'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-ff-3',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-fries',
    name: 'Veg Pops',
    description: 'Golden-fried bite-sized potato & vegetable herb nuggets with crunchy coating.',
    image: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=600&auto=format&fit=crop&q=80',
    price: 70,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: false,
    preparationTime: '6 mins',
    displayOrder: 3,
    tags: ['Bite Sized', 'Veg'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-ff-4',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-fries',
    name: 'Cheese Loaded French Fries',
    description: 'Crispy fries smothered in rich melted cheddar cheese sauce and garnished with parsley.',
    image: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?w=600&auto=format&fit=crop&q=80',
    price: 70,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '6 mins',
    displayOrder: 4,
    tags: ['Cheese Loaded', 'Popular'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-ff-5',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-fries',
    name: 'Spicy Cheese Loaded French Fries',
    description: 'Fries drenched in melted cheese sauce, sprinkled with jalapeño flakes and fiery chili herbs.',
    image: 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=600&auto=format&fit=crop&q=80',
    price: 90,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: false,
    preparationTime: '6 mins',
    displayOrder: 5,
    tags: ['Spicy Cheese', 'Hot'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-ff-6',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-fries',
    name: 'Cheese Loaded Chicken Fries',
    description: 'Golden fries loaded with crispy seasoned shredded chicken bits, cheese sauce, and special dressing.',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=600&auto=format&fit=crop&q=80',
    price: 110,
    isVegetarian: false,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '7-8 mins',
    displayOrder: 6,
    tags: ['Loaded Heavy', 'Chicken & Cheese'],
    createdAt: now,
    updatedAt: now,
  },

  // ==========================================
  // 3. HOT CHOCOLATE
  // ==========================================
  {
    _id: 'ef-hc-1',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-hot-chocolate',
    name: 'Hot Chocolate',
    description: 'Warm, thick, and creamy artisanal cocoa drink brewed with real melted chocolate and steamed milk.',
    image: 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=600&auto=format&fit=crop&q=80',
    price: 60,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: false,
    preparationTime: '4 mins',
    displayOrder: 1,
    tags: ['Warm', 'Artisanal Cocoa'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-hc-2',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-hot-chocolate',
    name: 'Hot Chocolate With Marshmallow',
    description: 'Velvety rich hot chocolate topped with fluffy soft mini marshmallows that melt with each sip.',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop&q=80',
    price: 80,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '4 mins',
    displayOrder: 2,
    tags: ['Marshmallows', 'Cozy'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-hc-3',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-hot-chocolate',
    name: 'Hot Chocolate With Ice Cream',
    description: 'Warm thick chocolate elixir served over a chilled scoop of velvety vanilla ice cream.',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&auto=format&fit=crop&q=80',
    price: 100,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '4 mins',
    displayOrder: 3,
    tags: ['Float', 'Decadent'],
    createdAt: now,
    updatedAt: now,
  },

  // ==========================================
  // 4. MOMOS
  // ==========================================
  {
    _id: 'ef-mo-1',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-momos',
    name: 'Paneer Momos (5 pcs)',
    description: 'Delicate dumplings filled with minced spiced paneer, onions, and fresh herbs, served with spicy red chutney.',
    image: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&auto=format&fit=crop&q=80',
    price: 70,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '6-8 mins',
    displayOrder: 1,
    tags: ['Pure Veg', 'Steamed/Fried'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-mo-2',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-momos',
    name: 'Chicken Momos (5 pcs)',
    description: 'Juicy minced chicken momos stuffed with garlic, green onions, and spices, served with fiery momo sauce.',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=600&auto=format&fit=crop&q=80',
    price: 80,
    isVegetarian: false,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '6-8 mins',
    displayOrder: 2,
    tags: ['Juicy', 'Chicken Special'],
    createdAt: now,
    updatedAt: now,
  },

  // ==========================================
  // 5. BURGERS
  // ==========================================
  {
    _id: 'ef-bg-1',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-burgers',
    name: 'Veg Burger',
    description: 'Crispy spiced vegetable patty topped with crunchy lettuce, ripe tomato, and creamy burger mayo in a toasted bun.',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=600&auto=format&fit=crop&q=80',
    price: 70,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: false,
    preparationTime: '6-8 mins',
    displayOrder: 1,
    tags: ['Veg Burger', 'Classic'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-bg-2',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-burgers',
    name: 'Veg Mini Burger (2 pcs)',
    description: 'Pair of delightful mini slider buns loaded with crispy veg patties, creamy dressing, and sliced pickles.',
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=600&auto=format&fit=crop&q=80',
    price: 70,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: false,
    preparationTime: '6-8 mins',
    displayOrder: 2,
    tags: ['2 Pcs Sliders', 'Veg'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-bg-3',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-burgers',
    name: 'Chicken Burger',
    description: 'Tender seasoned chicken patty layered with lettuce, onions, and house mayonnaise in a soft toasted sesame bun.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
    price: 90,
    isVegetarian: false,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '7-9 mins',
    displayOrder: 3,
    tags: ['Chicken Classic', 'Bestseller'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-bg-4',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-burgers',
    name: 'Chicken Mini Burger (2 pcs)',
    description: 'Two tasty mini chicken sliders loaded with juicy chicken patties, crisp lettuce, and special sauce.',
    image: 'https://images.unsplash.com/photo-1521305916504-4a1121188589?w=600&auto=format&fit=crop&q=80',
    price: 90,
    isVegetarian: false,
    isAvailable: true,
    isFeatured: false,
    preparationTime: '7-9 mins',
    displayOrder: 4,
    tags: ['2 Pcs Sliders', 'Chicken'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-bg-5',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-burgers',
    name: 'Spicy Chicken Burger',
    description: 'Fiery spiced crispy chicken breast, sliced jalapeños, spicy peri mayo, and crisp lettuce.',
    image: 'https://images.unsplash.com/photo-1610440042657-612c34d95e9f?w=600&auto=format&fit=crop&q=80',
    price: 100,
    isVegetarian: false,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '8-10 mins',
    displayOrder: 5,
    tags: ['Spicy', 'Hot & Crunchy'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-bg-6',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-burgers',
    name: 'Nashville Chicken Burger',
    description: 'Southern Nashville style cayenne glazed fried chicken patty, creamy coleslaw, and crunchy pickles in brioche bun.',
    image: 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=600&auto=format&fit=crop&q=80',
    price: 100,
    isVegetarian: false,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '8-10 mins',
    displayOrder: 6,
    tags: ['Nashville Hot', 'Chef Special'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-bg-7',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-burgers',
    name: 'Spicy Chicken Mini Burger (2 pcs)',
    description: 'Double mini slider burgers filled with fiery chili-seasoned chicken patties and spicy sauce.',
    image: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=600&auto=format&fit=crop&q=80',
    price: 100,
    isVegetarian: false,
    isAvailable: true,
    isFeatured: false,
    preparationTime: '7-9 mins',
    displayOrder: 7,
    tags: ['2 Pcs Spiced Sliders'],
    createdAt: now,
    updatedAt: now,
  },

  // ==========================================
  // 6. SWEETS (WAFFLES)
  // ==========================================
  {
    _id: 'ef-wf-1',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-waffles',
    name: 'Plain Waffle With Double Chocolate',
    description: 'Freshly baked Belgian golden waffle drenched with warm dark and milk chocolate drizzle.',
    image: 'https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=600&auto=format&fit=crop&q=80',
    price: 80,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: false,
    preparationTime: '5-7 mins',
    displayOrder: 1,
    tags: ['Double Choco', 'Sweet'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-wf-2',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-waffles',
    name: 'Choco Waffle With Double Chocolate',
    description: 'Rich dark chocolate cocoa waffle topped with decadent melted fudge and chocolate sauce.',
    image: 'https://images.unsplash.com/photo-1568051243851-f9b136146e97?w=600&auto=format&fit=crop&q=80',
    price: 90,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '5-7 mins',
    displayOrder: 2,
    tags: ['Choco Base', 'Rich'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-wf-3',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-waffles',
    name: 'Red Velvet Waffle With Double Chocolate',
    description: 'Vibrant red velvet waffle drizzled with contrasting layers of white and dark chocolate sauce.',
    image: 'https://images.unsplash.com/photo-1598214886806-c87b84b7078b?w=600&auto=format&fit=crop&q=80',
    price: 90,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '5-7 mins',
    displayOrder: 3,
    tags: ['Red Velvet', 'Special'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-wf-4',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-waffles',
    name: 'Butterscotch Waffle',
    description: 'Warm crisp waffle layered with rich buttery caramel butterscotch crunch and golden sauce.',
    image: 'https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=600&auto=format&fit=crop&q=80',
    price: 100,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: false,
    preparationTime: '5-7 mins',
    displayOrder: 4,
    tags: ['Butterscotch Crunch'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-wf-5',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-waffles',
    name: 'Choco With Biscoff Waffle',
    description: 'Fresh Belgian waffle smothered in spiced caramelized Lotus Biscoff spread and chocolate drizzle.',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
    price: 100,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '5-7 mins',
    displayOrder: 5,
    tags: ['Lotus Biscoff', 'Top Pick'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-wf-6',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-waffles',
    name: 'Classic Blueberry Waffle',
    description: 'Golden waffle topped with luscious sweet and tart blueberry compote and light dusting of sugar.',
    image: 'https://images.unsplash.com/photo-1459789034005-ba29c5783491?w=600&auto=format&fit=crop&q=80',
    price: 100,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: false,
    preparationTime: '5-7 mins',
    displayOrder: 6,
    tags: ['Blueberry', 'Fruity'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-wf-7',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-waffles',
    name: 'Classic Strawberry Waffle',
    description: 'Crisp waffle loaded with sweet strawberry preserve, fruit glaze, and white chocolate swirls.',
    image: 'https://images.unsplash.com/photo-1528751014936-863e6e7a319c?w=600&auto=format&fit=crop&q=80',
    price: 100,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: false,
    preparationTime: '5-7 mins',
    displayOrder: 7,
    tags: ['Strawberry Delight'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-wf-8',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-waffles',
    name: 'Choco With KitKat Waffle',
    description: 'Mouthwatering waffle generously topped with crushed KitKat wafer bars and molten chocolate sauce.',
    image: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?w=600&auto=format&fit=crop&q=80',
    price: 100,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '5-7 mins',
    displayOrder: 8,
    tags: ['KitKat Crunch', 'Bestseller'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-wf-9',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-waffles',
    name: 'Red Velvet Waffle With Strawberry Flavor',
    description: 'Red velvet waffle topped with strawberry syrup glaze, strawberry bits, and creamy white chocolate.',
    image: 'https://images.unsplash.com/photo-1584776296944-ab6fb57b0bdd?w=600&auto=format&fit=crop&q=80',
    price: 100,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: false,
    preparationTime: '5-7 mins',
    displayOrder: 9,
    tags: ['Red Velvet Strawberry'],
    createdAt: now,
    updatedAt: now,
  },

  // ==========================================
  // 7. MOJITO
  // ==========================================
  {
    _id: 'ef-mj-1',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-mojito',
    name: 'Mint Lemon Mojito',
    description: 'Refreshing sparkling cooler muddled with fresh mint leaves, lime slices, sugar syrup, and soda on ice.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    price: 50,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '2-3 mins',
    displayOrder: 1,
    tags: ['Chilled', 'Mint Lime'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-mj-2',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-mojito',
    name: 'Blueberry Mojito',
    description: 'Chilled bubbly soda with rich blueberry fruit essence, garden mint, lime, and crushed ice.',
    image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=600&auto=format&fit=crop&q=80',
    price: 50,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '2-3 mins',
    displayOrder: 2,
    tags: ['Blueberry Cooler'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-mj-3',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-mojito',
    name: 'Strawberry Mojito',
    description: 'Sweet and tangy strawberry soda mocktail with mint leaves, lemon squeeze, and ice cubes.',
    image: 'https://images.unsplash.com/photo-1556881286-fc6915169721?w=600&auto=format&fit=crop&q=80',
    price: 50,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: false,
    preparationTime: '2-3 mins',
    displayOrder: 3,
    tags: ['Strawberry Fizz'],
    createdAt: now,
    updatedAt: now,
  },

  // ==========================================
  // 8. WRAPS / ROLLS
  // ==========================================
  {
    _id: 'ef-rl-1',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-rolls',
    name: 'Veg Roll',
    description: 'Crispy warm wrap stuffed with seasoned vegetables, paneer cubes, sliced onions, and mint mayo chutney.',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&auto=format&fit=crop&q=80',
    price: 70,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: false,
    preparationTime: '5-7 mins',
    displayOrder: 1,
    tags: ['Veg Roll', 'Tawa Crisp'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-rl-2',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-rolls',
    name: 'Chicken Roll',
    description: 'Flaky parotta roll packed with tender roasted chicken chunks, sliced onions, and tangy sauce.',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&auto=format&fit=crop&q=80',
    price: 90,
    isVegetarian: false,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '6-8 mins',
    displayOrder: 2,
    tags: ['Chicken Roll', 'Bestseller'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-rl-3',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-rolls',
    name: 'Nashville Chicken Roll',
    description: 'Spicy cayenne-seasoned Nashville fried chicken strips with slaw and special sauce wrapped in warm tortilla.',
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=600&auto=format&fit=crop&q=80',
    price: 100,
    isVegetarian: false,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '6-8 mins',
    displayOrder: 3,
    tags: ['Nashville Spicy'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-rl-4',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-rolls',
    name: 'Spicy Cheese Loaded Jumbo',
    description: 'Extra large jumbo roll loaded with double chicken, melted cheese sauce, jalapeños, and spiced herbs.',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&auto=format&fit=crop&q=80',
    price: 110,
    isVegetarian: false,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '7-9 mins',
    displayOrder: 4,
    tags: ['Jumbo Loaded', 'Double Cheese'],
    createdAt: now,
    updatedAt: now,
  },

  // ==========================================
  // 9. EXTRA
  // ==========================================
  {
    _id: 'ef-ex-1',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-extra',
    name: 'Parcel Charge',
    description: 'Eco-friendly food-grade hot takeaway packing container.',
    image: 'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=600&auto=format&fit=crop&q=80',
    price: 5,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: false,
    preparationTime: 'Instant',
    displayOrder: 1,
    tags: ['Packaging'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'ef-ex-2',
    shopId: 'shop-eatandfly',
    categoryId: 'cat-extra',
    name: 'Extra Cheese',
    description: 'Extra portion of melted warm cheddar cheese sauce poured on your order.',
    image: 'https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?w=600&auto=format&fit=crop&q=80',
    price: 10,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: false,
    preparationTime: 'Instant',
    displayOrder: 2,
    tags: ['Extra Addon'],
    createdAt: now,
    updatedAt: now,
  },
];
