import { User, Shop, Category, FoodItem } from '../types';

const now = new Date().toISOString();

export const defaultUsers: User[] = [
  {
    _id: 'user-annapoorna',
    name: 'Murugan Swaminathan',
    email: 'owner@annapoorna.com',
    phone: '+91 98421 87654',
    role: 'owner',
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'user-streetbites',
    name: 'Karthik Raja',
    email: 'karthik@streetbites.com',
    phone: '+91 97500 12345',
    role: 'owner',
    createdAt: now,
    updatedAt: now,
  },
];

export const defaultShops: Shop[] = [
  {
    _id: 'shop-annapoorna',
    ownerId: 'user-annapoorna',
    name: 'Annapoorna Food Truck',
    slug: 'annapoorna-food-truck',
    logo: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=300&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&auto=format&fit=crop&q=80',
    description: 'Authentic roadside hot bites, tawa fried rice, sizzling rolls & signature chillers freshly prepared in our 4-wheel mobile kitchen.',
    phone: '+91 98421 87654',
    whatsappNumber: '+919842187654',
    address: 'Near Central Bus Stand, Brough Road',
    location: 'Erode, Tamil Nadu',
    openingTime: '05:30 PM',
    closingTime: '11:30 PM',
    isOpen: true,
    currency: '₹',
    orderingEnabled: true,
    whatsappOrderingEnabled: true,
    upiId: 'annapoornafood@upi',
    customTagline: 'Fresh & Hot From Our Food Truck Right To You!',
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'shop-streetbites',
    ownerId: 'user-streetbites',
    name: 'Street Bites Food Truck',
    slug: 'street-bites-food-truck',
    logo: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=300&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&auto=format&fit=crop&q=80',
    description: 'Crispy street snacks, loaded kathi rolls, shawarma & refreshing fresh juices on wheels.',
    phone: '+91 97500 12345',
    whatsappNumber: '+919750012345',
    address: 'Opposite VOC Park Ground, Gandhiji Road',
    location: 'Erode, Tamil Nadu',
    openingTime: '04:00 PM',
    closingTime: '11:00 PM',
    isOpen: true,
    currency: '₹',
    orderingEnabled: true,
    whatsappOrderingEnabled: true,
    upiId: 'streetbites@okhdfcbank',
    customTagline: 'Scan • Explore • Savor the crunch',
    createdAt: now,
    updatedAt: now,
  },
];

export const defaultCategories: Category[] = [
  { _id: 'cat-special', shopId: 'shop-annapoorna', name: "Today's Special", description: "Chef's daily hot recommendations", displayOrder: 1, isActive: true, createdAt: now, updatedAt: now },
  { _id: 'cat-rice', shopId: 'shop-annapoorna', name: "Rice & Noodles", description: "Hot tossed wok dishes on flame", displayOrder: 2, isActive: true, createdAt: now, updatedAt: now },
  { _id: 'cat-rolls', shopId: 'shop-annapoorna', name: "Rolls & Wraps", description: "Crispy tawa parotta rolls", displayOrder: 3, isActive: true, createdAt: now, updatedAt: now },
  { _id: 'cat-snacks', shopId: 'shop-annapoorna', name: "Starters & Snacks", description: "Deep fried & tossed evening munchies", displayOrder: 4, isActive: true, createdAt: now, updatedAt: now },
  { _id: 'cat-beverages', shopId: 'shop-annapoorna', name: "Beverages & Juices", description: "Freshly squeezed & refreshing drinks", displayOrder: 5, isActive: true, createdAt: now, updatedAt: now },
  { _id: 'cat-desserts', shopId: 'shop-annapoorna', name: "Sweet Treats", description: "Quick sweet finishers", displayOrder: 6, isActive: true, createdAt: now, updatedAt: now },
  // Street Bites categories
  { _id: 'cat-sb-rolls', shopId: 'shop-streetbites', name: "Kathi Rolls & Shawarma", description: "Fresh rolls with mint chutney", displayOrder: 1, isActive: true, createdAt: now, updatedAt: now },
  { _id: 'cat-sb-burgers', shopId: 'shop-streetbites', name: "Desi Burgers & Fries", description: "Toasted buns with hot patties", displayOrder: 2, isActive: true, createdAt: now, updatedAt: now },
  { _id: 'cat-sb-drinks', shopId: 'shop-streetbites', name: "Mojitos & Shakes", description: "Ice cold crushers", displayOrder: 3, isActive: true, createdAt: now, updatedAt: now },
];

export const defaultFoods: FoodItem[] = [
  // Annapoorna foods
  {
    _id: 'food-1',
    shopId: 'shop-annapoorna',
    categoryId: 'cat-rice',
    name: 'Chicken Fried Rice',
    description: 'Aromatic basmati rice tossed with tender shredded chicken, spring onions, eggs, and freshly cracked pepper in our signature food truck wok style.',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&auto=format&fit=crop&q=80',
    price: 130,
    isVegetarian: false,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '8-10 mins',
    displayOrder: 1,
    tags: ['Bestseller', 'Hot'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'food-2',
    shopId: 'shop-annapoorna',
    categoryId: 'cat-rice',
    name: 'Schezwan Egg Noodles',
    description: 'Spicy wok-tossed hakka noodles with double egg, crunchy cabbage, capsicum, and homemade fiery schezwan sauce.',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&auto=format&fit=crop&q=80',
    price: 110,
    isVegetarian: false,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '6-8 mins',
    displayOrder: 2,
    tags: ['Spicy', 'Popular'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'food-3',
    shopId: 'shop-annapoorna',
    categoryId: 'cat-rice',
    name: 'Veg Paneer Fried Rice',
    description: 'Fresh malai paneer cubes tossed with garden green peas, carrots, beans, and seasoned basmati rice.',
    image: 'https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?w=600&auto=format&fit=crop&q=80',
    price: 120,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: false,
    preparationTime: '7-9 mins',
    displayOrder: 3,
    tags: ['Pure Veg'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'food-4',
    shopId: 'shop-annapoorna',
    categoryId: 'cat-rolls',
    name: 'Double Egg Chicken Roll',
    description: 'Crispy flaky tawa parotta layered with 2 fluffy eggs, filled with roasted spiced chicken pieces, sliced red onions, green chilies, and lemon zest.',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&auto=format&fit=crop&q=80',
    price: 90,
    isVegetarian: false,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '5-7 mins',
    displayOrder: 1,
    tags: ['Chef Pick', 'Heavy Bite'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'food-5',
    shopId: 'shop-annapoorna',
    categoryId: 'cat-rolls',
    name: 'Paneer Tikka Roll',
    description: 'Charred smoky paneer cubes rolled in crisp tawa roti with mint mayo chutney and tangy pickled onions.',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&auto=format&fit=crop&q=80',
    price: 80,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: false,
    preparationTime: '5-6 mins',
    displayOrder: 2,
    tags: ['Veg Special'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'food-6',
    shopId: 'shop-annapoorna',
    categoryId: 'cat-snacks',
    name: 'Chicken 65 (Boneless)',
    description: 'Deep fried crispy chicken chunks marinated in south Indian curd-chili masala and tossed with fresh curry leaves and fried garlic.',
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=600&auto=format&fit=crop&q=80',
    price: 140,
    isVegetarian: false,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '10 mins',
    displayOrder: 1,
    tags: ['Crispy', 'Snack Bestseller'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'food-7',
    shopId: 'shop-annapoorna',
    categoryId: 'cat-snacks',
    name: 'Crispy Veg Momos (6 Pcs)',
    description: 'Steamed then golden-crisp fried vegetable dumplings served with spicy garlic-red chili dipping chutney.',
    image: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&auto=format&fit=crop&q=80',
    price: 80,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: false,
    preparationTime: '6-8 mins',
    displayOrder: 2,
    tags: ['Crispy'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'food-8',
    shopId: 'shop-annapoorna',
    categoryId: 'cat-snacks',
    name: 'Chili Gobi Dry',
    description: 'Crunchy battered cauliflower florets tossed with capsicum, garlic, green chilies, and dark soya sauce.',
    image: 'https://images.unsplash.com/photo-1567337710282-00832b415979?w=600&auto=format&fit=crop&q=80',
    price: 90,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: false,
    preparationTime: '7-9 mins',
    displayOrder: 3,
    tags: ['Pure Veg', 'Spicy'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'food-9',
    shopId: 'shop-annapoorna',
    categoryId: 'cat-beverages',
    name: 'Fresh Mint Lime Soda',
    description: 'Chilled bubbly soda infused with freshly squeezed lemons, crushed garden mint, rock salt, and sugar syrup.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    price: 40,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: false,
    preparationTime: '2 mins',
    displayOrder: 1,
    tags: ['Chilled', 'Refreshing'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'food-10',
    shopId: 'shop-annapoorna',
    categoryId: 'cat-beverages',
    name: 'Kulukki Sarbath (Pineapple)',
    description: 'Famous shaken ice cooler with crushed pineapple, green chilies, sabja seeds, and tangy sweet lemon.',
    image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=600&auto=format&fit=crop&q=80',
    price: 50,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '3 mins',
    displayOrder: 2,
    tags: ['Kerala Style', 'Special Cooler'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'food-11',
    shopId: 'shop-annapoorna',
    categoryId: 'cat-desserts',
    name: 'Hot Gulab Jamun with Ice Cream (2 Pcs)',
    description: 'Piping hot melt-in-mouth milk dough dumplings soaked in cardamom rose syrup paired with a scoop of vanilla ice cream.',
    image: 'https://images.unsplash.com/photo-1589119908995-c6837fa14d48?w=600&auto=format&fit=crop&q=80',
    price: 60,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '2 mins',
    displayOrder: 1,
    tags: ['Dessert', 'Sweet'],
    createdAt: now,
    updatedAt: now,
  },

  // Street Bites food items
  {
    _id: 'food-sb-1',
    shopId: 'shop-streetbites',
    categoryId: 'cat-sb-rolls',
    name: 'Loaded Chicken Shawarma Roll',
    description: 'Juicy spiced pulled chicken wrapped in kuboos with garlic toum sauce, pickled cucumbers, and french fries.',
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=600&auto=format&fit=crop&q=80',
    price: 110,
    isVegetarian: false,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '5-7 mins',
    displayOrder: 1,
    tags: ['Bestseller'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'food-sb-2',
    shopId: 'shop-streetbites',
    categoryId: 'cat-sb-burgers',
    name: 'Crispy Zinger Chicken Burger',
    description: 'Extra crunchy fried chicken breast fillet inside toasted brioche bun with creamy coleslaw and spicy mayo.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
    price: 120,
    isVegetarian: false,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '8-10 mins',
    displayOrder: 1,
    tags: ['Juicy'],
    createdAt: now,
    updatedAt: now,
  },
  {
    _id: 'food-sb-3',
    shopId: 'shop-streetbites',
    categoryId: 'cat-sb-drinks',
    name: 'Virgin Blue Curacao Mojito',
    description: 'Refreshing citrus blue curaçao drink with mint leaves, lemon slices, and crushed ice.',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
    price: 60,
    isVegetarian: true,
    isAvailable: true,
    isFeatured: true,
    preparationTime: '3 mins',
    displayOrder: 1,
    tags: ['Chilled'],
    createdAt: now,
    updatedAt: now,
  },
];
